apiVersion: 1

contactPoints:
  - orgId: 1
    name: server-channel
    receivers:
      - uid: ce0x6iqtr6i2pf
        type: slack
        settings:
          icon_emoji: ':warning:'
          url: ${GF_SERVER_CHANNEL}
          username: Server Up/Down Warn
          text: |
            *Alert:* {{ .CommonAnnotations.summary }}
            *Description:* {{ .CommonAnnotations.description }}
            *Severity:* {{ .Labels.severity }}
        disableResolveMessage: true


  - orgId: 1
    name: traffic-channel
    receivers:
      - uid: ae0x12fed8r29f
        type: slack
        settings:
          icon_emoji: ':fire:'
          url: ${GF_TRAFFIC_CHANNEL}
          username: Traffic Warn
          text: |
            *Alert:* {{ .CommonAnnotations.summary }}
            *Description:* {{ .CommonAnnotations.description }}
            *Severity:* {{ .Labels.severity }}
        disableResolveMessage: false