spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: commerce-service
          uri: lb://commerce-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/orders/**, /api/v1/vendors/**, /actuator/prometheus
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
      discovery:
        locator:
          enabled: true

server:
  port: 19091