services:
  eureka-server:
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/eureka
    container_name: eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}

  gateway:
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/gateway
    container_name: gateway
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GATEWAY_SERVER_PORT=${GATEWAY_SERVER_PORT}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - eureka-server