services:
  delivery_db:
    image: mongo:latest
    container_name: delivery_db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${DELIVERY_MONGODB_PORT}:27017"

  commerce_db:
    image: postgres:latest
    container_name: commerce_db
    environment:
      - POSTGRES_DB=${COMMERCE_DB}
      - POSTGRES_USER=${COMMERCE_USER}
      - POSTGRES_PASSWORD=${COMMERCE_PASSWORD}
    ports:
      - "${COMMERCE_PORT}:5432"
    volumes:
      - ./db-init/commerce/init-commerce.sql:/docker-entrypoint-initdb.d/init-commerce.sql

  payment_db:
    image: postgres:latest
    container_name: payment_db
    environment:
      - POSTGRES_DB=${PAYMENT_DB}
      - POSTGRES_USER=${PAYMENT_USER}
      - POSTGRES_PASSWORD=${PAYMENT_PASSWORD}
    ports:
      - "${PAYMENT_PORT}:5432"
    volumes:
      - ./db-init/payment/init-payment.sql:/docker-entrypoint-initdb.d/init-payment.sql

  user_db:
    image: postgres:latest
    container_name: user_db
    environment:
      - POSTGRES_DB=${USER_DB}
      - POSTGRES_USER=${USER_USER}
      - POSTGRES_PASSWORD=${USER_PASSWORD}
    ports:
      - "${USER_PORT}:5432"
    volumes:
      - ./db-init/user/init-user.sql:/docker-entrypoint-initdb.d/init-user.sql

  notification_db:
    image: postgres:latest
    container_name: notification_db
    environment:
      - POSTGRES_DB=${NOTIFICATION_DB}
      - POSTGRES_USER=${NOTIFICATION_USER}
      - POSTGRES_PASSWORD=${NOTIFICATION_PASSWORD}
    ports:
      - "${NOTIFICATION_PORT}:5432"
    volumes:
      - ./db-init/notification/init-notification.sql:/docker-entrypoint-initdb.d/init-notification.sql