services:
  commerce-service:
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/commerce
    container_name: commerce-service
    ports:
      - "${COMMERCE_SERVER_PORT}:${COMMERCE_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - COMMERCE_SERVER_PORT=${COMMERCE_SERVER_PORT}
      - COMMERCE_DB_URL=${COMMERCE_DB_URL}
      - COMMERCE_DB_USERNAME=${COMMERCE_DB_USERNAME}
      - COMMERCE_DB_PASSWORD=${COMMERCE_DB_PASSWORD}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  payment-service:
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/payment
    container_name: payment-service
    ports:
      - "${PAYMENT_SERVER_PORT}:${PAYMENT_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PAYMENT_SERVER_PORT=${PAYMENT_SERVER_PORT}
      - PAYMENT_DB_URL=${PAYMENT_DB_URL}
      - PAYMENT_DB_USERNAME=${PAYMENT_DB_USERNAME}
      - PAYMENT_DB_PASSWORD=${PAYMENT_DB_PASSWORD}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}