services:
  delivery-service:
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/delivery:latest
    build:
      context: ../delivery-service
      dockerfile: Dockerfile
    container_name: delivery
    ports:
      - "${DELIVERY_SERVER_PORT}:${DELIVERY_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DELIVERY_SERVER_PORT=${DELIVERY_SERVER_PORT}
      - DELIVERY_MONGODB_HOST=${DELIVERY_MONGODB_HOST}
      - DELIVERY_MONGODB_PORT=${DELIVERY_MONGODB_PORT}
      - DELIVERY_MONGODB_DATABASE=${DELIVERY_MONGODB_DATABASE}
      - DELIVERY_MONGODB_USERNAME=${DELIVERY_MONGODB_USERNAME}
      - DELIVERY_MONGODB_PASSWORD=${DELIVERY_MONGODB_PASSWORD}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_ENDPOINT=${ZIPKIN_ENDPOINT}
      - REDIS_SENTINEL_PORT1=${REDIS_SENTINEL_PORT1}
      - REDIS_SENTINEL_PORT2=${REDIS_SENTINEL_PORT2}
      - REDIS_SENTINEL_PORT3=${REDIS_SENTINEL_PORT3}
      - LOKI_URL=${LOKI_URL}

  notification-service:
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/notification:latest
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    container_name: notification
    ports:
      - "${NOTIFICATION_SERVER_PORT}:${NOTIFICATION_SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - NOTIFICATION_SERVER_PORT=${NOTIFICATION_SERVER_PORT}
      - NOTIFICATION_DB_URL=${NOTIFICATION_DB_URL}
      - NOTIFICATION_DB_USERNAME=${NOTIFICATION_DB_USERNAME}
      - NOTIFICATION_DB_PASSWORD=${NOTIFICATION_DB_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SLACK_WORKSPACE_URL=${SLACK_WORKSPACE_URL}
      - ZIPKIN_ENDPOINT=${ZIPKIN_ENDPOINT}
      - LOKI_URL=${LOKI_URL}