global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:19090']
        labels:
          service: 'server'

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:19091']
        labels:
          service: 'gateway'

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:19092']
        labels:
          service: 'auth'

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:19093']
        labels:
          service: 'user'

  - job_name: 'commerce-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:19094']
        labels:
          service: 'commerce'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:19095']
        labels:
          service: 'payment'

  - job_name: 'delivery-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:19096']
        labels:
          service: 'delivery'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:19097']
        labels:
          service: 'notification'

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          service: 'node-exporter'