name: Deploy to AWS ECR

on:
  push:
    branches: [ "feature/connect-ecr" ]
      
jobs:
  deploy:
    name: Deploy to ECR
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
    - name: Grant execute permission for Gradle Wrapper in root directory
      run: chmod +x ./gradlew
      
    - name: Build with Gradle Wrapper
      run: ./gradlew bootjar

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push docker image to AWS ECR
      run: |
        docker compose -f docker/docker-compose.service.yml build
        
        services=("eureka-server" "gateway" "auth-service" "user-service" "commerce-service" "payment-service" "delivery-service" "notification-service")
        for service in "${services[@]}"; do
          docker tag ${ECR_REGISTRY}/${ECR_NAMESPACE}/$service:latest $ECR_REGISTRY/${ECR_NAMESPACE}/$service:$IMAGE_TAG
          docker push $ECR_REGISTRY/${ECR_NAMESPACE}/$service:$IMAGE_TAG
          echo "$service image is built and pushed to AWS ECR"
        done
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_NAMESPACE: ${{ secrets.ECR_NAMESPACE }}
        IMAGE_TAG: "latest"
        
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        
        KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        
        EUREKA_SERVER_PORT: ${{ secrets.EUREKA_SERVER_PORT }}
        EUREKA_SERVER_URL: ${{ secrets.EUREKA_SERVER_URL }}
        EUREKA_HOSTNAME: ${{ secrets.EUREKA_HOSTNAME }}
        
        GATEWAY_SERVER_PORT: ${{ secrets.GATEWAY_SERVER_PORT }}
        
        AUTH_SERVER_PORT: ${{ secrets.AUTH_SERVER_PORT }}
        
        USER_SERVER_PORT: ${{ secrets.USER_SERVER_PORT }}
        USER_DB_URL: ${{ secrets.USER_DB_URL }}
        USER_DB_USERNAME: ${{ secrets.USER_DB_USERNAME }}
        USER_DB_PASSWORD: ${{ secrets.USER_DB_PASSWORD }}
        
        NOTIFICATION_SERVER_PORT: ${{ secrets.NOTIFICATION_SERVER_PORT }}
        NOTIFICATION_DB_URL: ${{ secrets.NOTIFICATION_DB_URL }}
        NOTIFICATION_DB_USERNAME: ${{ secrets.NOTIFICATION_DB_USERNAME }}
        NOTIFICATION_DB_PASSWORD: ${{ secrets.NOTIFICATION_DB_PASSWORD }}
        
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        
        PAYMENT_SERVER_PORT: ${{ secrets.PAYMENT_SERVER_PORT }}
        PAYMENT_DB_URL: ${{ secrets.PAYMENT_DB_URL }}
        PAYMENT_DB_USERNAME: ${{ secrets.PAYMENT_DB_USERNAME }}
        PAYMENT_DB_PASSWORD: ${{ secrets.PAYMENT_DB_PASSWORD }}
        
        DELIVERY_SERVER_PORT: ${{ secrets.DELIVERY_SERVER_PORT }}
        DELIVERY_MONGODB_HOST: ${{ secrets.DELIVERY_MONGODB_HOST }}
        DELIVERY_MONGODB_PORT: ${{ secrets.DELIVERY_MONGODB_PORT }}
        DELIVERY_MONGODB_DATABASE: ${{ secrets.DELIVERY_MONGODB_DATABASE }}
        DELIVERY_MONGODB_USERNAME: ${{ secrets.DELIVERY_MONGODB_USERNAME }}
        DELIVERY_MONGODB_PASSWORD: ${{ secrets.DELIVERY_MONGODB_PASSWORD }}
        
        COMMERCE_SERVER_PORT: ${{ secrets.COMMERCE_SERVER_PORT }}
        COMMERCE_DB_URL: ${{ secrets.COMMERCE_DB_URL }}
        COMMERCE_DB_USERNAME: ${{ secrets.COMMERCE_DB_USERNAME }}
        COMMERCE_DB_PASSWORD: ${{ secrets.COMMERCE_DB_PASSWORD }}
        
        COMMERCE_DB: ${{ secrets.COMMERCE_DB }}
        COMMERCE_USER: ${{ secrets.COMMERCE_USER }}
        COMMERCE_PASSWORD: ${{ secrets.COMMERCE_PASSWORD }}
        COMMERCE_PORT: ${{ secrets.COMMERCE_PORT }}
        
        PAYMENT_DB: ${{ secrets.PAYMENT_DB }}
        PAYMENT_USER: ${{ secrets.PAYMENT_USER }}
        PAYMENT_PASSWORD: ${{ secrets.PAYMENT_PASSWORD }}
        PAYMENT_PORT: ${{ secrets.PAYMENT_PORT }}
        
        USER_DB: ${{ secrets.USER_DB }}
        USER_USER: ${{ secrets.USER_USER }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        USER_PORT: ${{ secrets.USER_PORT }}
        
        NOTIFICATION_DB: ${{ secrets.NOTIFICATION_DB }}
        NOTIFICATION_USER: ${{ secrets.NOTIFICATION_USER }}
        NOTIFICATION_PASSWORD: ${{ secrets.NOTIFICATION_PASSWORD }}
        NOTIFICATION_PORT: ${{ secrets.NOTIFICATION_PORT }}
        
        KAFKA_CLUSTER_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_CLUSTER_BOOTSTRAP_SERVERS }}
        
        WEBHOOK_FOR_SERVER: ${{ secrets.WEBHOOK_FOR_SERVER }}
        WEBHOOK_FOR_TRAFFIC: ${{ secrets.WEBHOOK_FOR_TRAFFIC }}
        SLACK_WORKSPACE_URL: ${{ secrets.SLACK_WORKSPACE_URL }}
